install:
- gem install asciidoctor
script:
- asciidoctor faq.adoc -o html/faq.html
env:
  global:
    - GH_REF: aminesabri/test_integration.git
    - secure: eK7pLyU1zQAlfmt3F0nuiNouRKBrHXG28hp2QlFm3Od8IumurxI2qeSvrgwynxf7p3puRFiQpPFW97G3KrbGi3T30cbFS5uBp9hx7y+9vFonKbQWBJDRulgI/kPpngWT70w6vqB8UMBmLbV9c0N1Cebd9y9ux6/Cm+zjXyBHG+NBJWji/CWRtREeiJgtKDKzDwrb5GCvhZ/CjeJW5O7wFORxA/4WAGKAjiaSTZXezuVjyHzkhO6Pwb/F95kAw8b8fbKr46WTgOlEsLsQFjX2J8sXtNtC+jtDqcNdWs6+TKJwwOrA3E7hH5B+idPS1ef0Zn8qU8K3jH6pzGre5GKEACaKuK49hNBbxt3pVi+q3baKzqPQHvVaAHdrfsOUb1HTIZmafN7dPRi3u3lG9AZmF6n49e0AjB3UB5gpBN4BNsibXAhsYNJjh5oqvvgywnEdQu1RXxZSJbVYxG4VHsf9q5OHmt0zZMWHarj8u2alFSGStHDjc7hXbL5N7gsrecZigeNEwSiUal1qAYt3OVCUyPtAvmLHGDPo1zPotP81HIQrPQt4Gs7Z3Nl9s0J2kybm8/8V9M8iTKIXmPlLUPacCVLvrpD78OWyCQkUKeBuWxhWpK150mbeVVr/HIXhyX8QsvI3lD1DCbEjo10cKZFgPFF/ckE5mfrU8QAW83Z2Rao=

after_success: 
- bash monscript.sh
