install:
- gem install asciidoctor
script:
- asciidoctor faq.adoc -o html/faq.html
env:
  global:
  - GH_REF: aminesabri/test_integration.git
  - secure: tn6OyCtpIMIcATv45S/R5KIxpnPmviZazhRM+ri5guRjIN2DKWME4F+fmQc3N9/J4N9dWCybHhfFuUAoXw03qkt+UiCgoDN+SIViUdy8SqWSoECcweOF2taRH98AD3Z1n5Yt5iGo4DWc1tthSmZGpfq0Nzl0vJpBHoEPUXu1sItnq4hVYiclgN4iCuXhcHEKSITehNjNvOgH0P5bTLVmBxuluLQnxmxs8llhCYMJYvNRI7ahT8C5/WsR8CnVj+jjMFN/4ddpu49yPjLJmCBja+NcsMROd+w7ZjlwGwq6BPHiyd4IJjyAj8nOShKA4X5ygLSaUyDaX2PIhGL6/2xpGRzEhBlBLMNtrlL3sgqK8VTdBTfzJm99EeTXxadBNg0NqQbSr7X2Ii9I0UtyP7GRiieyoLKJkXXKbp3LHT2dHFoQCmyDoFZtSajFwR3ERZlcB22hLeaq9USRDsLh5AOG2+adZ9ZqEVRvWCmHKPql+cnUUSC5K2fJR7xjnNfdWhPISZSwxkqgrpiPResPccj2MQGR6D2Z1LxXAhFvazlGbUBug6gEZHCavR9lmr3Pz2nHEJnx3xJ/ZLSzVshzyVPmscVUOeBrRwrw2joP0MQSxpQQa1Wgp+B0ORZHCK27U1ANrfKLJqfsTlEbVoTBKudJWoQUFVltQD0tZEFghN6amfw=

after_success:
- bash monscript.sh

